plugin_group=com.azuredoom.hytalepublisher
plugin_version=1.1.7
plugin_implementation_class=com.azuredoom.hytalepublisher.HytalePublisherPlugin
plugin_display_name=HytalePublisher
plugin_description=A Gradle plugin that automates building and publishing Hytale mods to multiple platforms, including CurseForge, Modtale, Modifold, and Thunderstore.io.

plugin_website=https://github.com/AzureDoom/HytalePublisher
plugin_vcs_url=https://github.com/AzureDoom/HytalePublisher

mod_id=HytalePublisher
maven_url=https://maven.azuredoom.com/mods
